<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration {public function up():void{
 Schema::create('payment_gateways',function(Blueprint $t){$t->id();$t->string('name');$t->string('slug')->unique();$t->boolean('status')->default(false);$t->string('environment')->default('test');$t->json('credentials')->nullable();$t->json('configuration')->nullable();$t->timestamps();});
 Schema::create('payments',function(Blueprint $t){$t->id();$t->foreignId('business_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('card_id')->nullable()->constrained('virtual_cards')->nullOnDelete();$t->string('gateway')->index();$t->decimal('amount',18,2);$t->char('currency',3)->default('INR');$t->string('reference')->unique();$t->string('gateway_payment_id')->nullable()->index();$t->string('gateway_order_id')->nullable()->index();$t->string('status')->default('created')->index();$t->json('gateway_response')->nullable();$t->json('metadata')->nullable();$t->timestamp('completed_at')->nullable();$t->timestamps();$t->index(['business_id','status']);});
 Schema::create('transactions',function(Blueprint $t){$t->id();$t->foreignId('business_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('card_id')->nullable()->constrained('virtual_cards')->nullOnDelete();$t->foreignId('payment_id')->nullable()->constrained()->nullOnDelete();$t->string('gateway')->nullable();$t->string('gateway_transaction_id')->nullable()->index();$t->string('transaction_type')->index();$t->decimal('amount',18,2);$t->decimal('fee',18,2)->default(0);$t->decimal('net_amount',18,2);$t->string('status')->index();$t->string('reference')->index();$t->string('description')->nullable();$t->json('metadata')->nullable();$t->timestamps();$t->softDeletes();$t->index(['card_id','transaction_type','status']);});
 Schema::create('webhook_events',function(Blueprint $t){$t->id();$t->string('gateway')->index();$t->string('event_id')->nullable();$t->string('event_type')->nullable();$t->string('payload_hash')->index();$t->json('payload');$t->timestamp('processed_at')->nullable();$t->timestamps();$t->unique(['gateway','payload_hash']);});
 Schema::create('audit_logs',function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('action');$t->string('auditable_type')->nullable();$t->unsignedBigInteger('auditable_id')->nullable();$t->ipAddress('ip_address')->nullable();$t->text('user_agent')->nullable();$t->json('metadata')->nullable();$t->timestamps();$t->index(['auditable_type','auditable_id']);});
 }public function down():void{Schema::dropIfExists('audit_logs');Schema::dropIfExists('webhook_events');Schema::dropIfExists('transactions');Schema::dropIfExists('payments');Schema::dropIfExists('payment_gateways');}};
